services:
  drupal:
    image: drupal:10-apache
    ports:
      - "9090:80"
    volumes:
      - drupal_modules:/var/www/html/modules
      - drupal_profiles:/var/www/html/profiles
      - drupal_sites:/var/www/html/sites
      - drupal_themes:/var/www/html/themes
    environment:
      DRUPAL_DB_HOST: drupal_db
      DRUPAL_DB_PORT: 5432
      DRUPAL_DB_NAME: drupal
      DRUPAL_DB_USER: drupal
      DRUPAL_DB_PASSWORD: drupal
    depends_on:
      - drupal_db
    networks:
      - drupal_network

  drupal_db:
    image: postgres:15
    environment:
      POSTGRES_DB: drupal
      POSTGRES_USER: drupal
      POSTGRES_PASSWORD: drupal
    volumes:
      - drupal_db_data:/var/lib/postgresql/data
    networks:
      - drupal_network

volumes:
  drupal_modules:
  drupal_profiles:
  drupal_sites:
  drupal_themes:
  drupal_db_data:

networks:
  drupal_network:
    driver: bridge
